### ISSUE TITLE
Set ReplyTo in email to WRT

### ISSUE THREAD

**Issue by Jambrose777** [thewca/db-sanity-check#31]
In the https://github.com/thewca/db-sanity-check/blob/main/src/main/java/org/worldcubeassociation/dbsanitycheck/service/impl/EmailServiceImpl.java We can add something like:
`helper.setReplyTo(WRT@worldcubeassociation.org);`

This will make it to where the WCT will no longer receive emails whenever WRT replies to Sanity Check Emails.

Further implementation instructions may be found here: https://www.tabnine.com/code/java/methods/javax.mail.internet.MimeMessage/setReplyTo

**Comment by gregorbg** [comment]
@campos20 Are you available to implement this suggestion?

**Comment by campos20** [comment]
> @campos20 Are you available to implement this suggestion?

Yes, I can handle this. I also wanted to improve the IAC of this project. Currently, we are using cloudformation and is quite boring to replace the variables. So, any configuration change is a bit painful right now. We need to take care of #32 before. I can probably handle this before Nov 1st, which is when the next auto triggered run will happen.
